version: "3"
services:
    react-app:
        container_name: space-x
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8078:80
        expose:
            - "8078"
        volumes:
            - ./src:/app/src
        restart: unless-stopped
